import { readFileSync, writeFileSync } from 'node:fs';
const items = [
  ['1-mapa-naplno','Mapa naplno','Mapa a detail na dotek.','Trebuchet MS / Segoe UI','#b72150'],
  ['2-cestovni-atlas','Cestovní atlas','Klidná sazba a přehledné srovnání.','Georgia / Arial','#005b65'],
  ['3-den-po-dni','Den po dni','Mapa propojená s denním plánem.','Bahnschrift / Segoe UI','#ad462e'],
];
const cards = items.map(([id,title,description,type,color],i)=>{
  const png=readFileSync(new URL(`${i+1}-mobile.png`,import.meta.url)).toString('base64');
  return `<article style="--accent:${color}"><header><span>0${i+1}</span><div><h2>${title}</h2><p>${description}</p></div></header><a href="${id}.html"><img src="data:image/png;base64,${png}" alt="Mobilní náhled ${title} při šířce 375 pixelů"></a><footer><span class="swatch"></span>${type}<a href="${id}.html">Otevřít návrh ↗</a></footer></article>`;
}).join('');
writeFileSync(new URL('prehled.html',import.meta.url),`<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tři směry pro mapu dovolené</title><style>*{box-sizing:border-box}body{margin:0;background:#fff;color:#213c40;font-family:'Segoe UI',Arial,sans-serif}.intro{padding:20px 38px 14px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #e0e6e4}h1{font-size:22px;letter-spacing:-.5px;margin:0}.intro p{font-size:11px;color:#647976;margin:0;max-width:390px;line-height:1.7}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:34px;padding:19px 38px}article{min-width:0}article header{display:flex;gap:12px;align-items:center;margin-bottom:14px}header>span{font-size:27px;color:var(--accent);font-weight:300}h2{font-size:17px;margin:0}header p{font-size:10px;color:#61736f;margin:4px 0 0}article>a{display:block;text-align:center;padding:0;background:#f0f4f4;border:1px solid #e0e7e4;border-radius:9px;overflow:hidden}img{height:570px;max-width:100%;object-fit:contain;vertical-align:bottom;box-shadow:0 0 24px #2e595212}footer{display:flex;gap:6px;align-items:center;margin-top:12px;font-size:9px;color:#687b76}.swatch{width:10px;height:10px;border-radius:50%;background:var(--accent)}footer a{margin-left:auto;color:var(--accent);font-size:11px;font-weight:650;text-decoration:none}.note{margin:0 38px;font-size:10px;color:#667b75;line-height:1.7}@media(max-width:700px){.intro{display:block;padding:20px}.intro p{margin-top:8px}.grid{grid-template-columns:1fr;padding:20px;gap:30px}img{height:auto;width:100%}.note{margin:0 20px 20px}}a:focus-visible{outline:3px solid #196bb4;outline-offset:4px}</style></head><body><div class="intro"><h1>Jak bude vypadat naše mapa?</h1><p>Tři návrhy rozhraní · kontrola při 375 px<br>Výběr vzhledu. O cestách rozhodujete vy.</p></div><main class="grid">${cards}</main><p class="note">V mapách jsou pouze schémata původních koridorů. Skutečné geometrie, kilometry, časy a další etapy doplní ověření dat.</p></body></html>`);
