import {PaidPasses} from './PaidPasses';
import {StopPhoto} from './StopPhoto';
import {ExcursionCards,ExcursionDetails,ExcursionSection} from './Excursions';
import {excursions} from './excursionData';
import type {ExcursionBase} from './types';
import {ExchangeRateContext,Money,CurrencyText} from './Money';
import exchange from '../data/exchange-rate.json';
import {lazy,Suspense,useCallback,useEffect,useMemo,useState} from 'react';
import type {CSSProperties} from 'react';
import {ArrowRight,ArrowUpRight,Check,ChevronDown,ClipboardList,Compass,Fuel,Info,Map as MapIcon,Plus,RotateCcw,Route as RouteIcon,Settings2,Trash2,TreePine,Utensils,Wallet,Waves,X} from 'lucide-react';
const MapView=lazy(()=>import('./MapView'));
const Roadbook=lazy(()=>import('./Roadbook'));
const TripDownload=lazy(()=>import('./Roadbook').then(m=>({default:m.TripDownload})));
function RoadbookPanel(props:{data:Dataset;route:Route;settings:Settings;selection?:Selection}){return <Suspense fallback={<p>Načítám tahák…</p>}><Roadbook {...props}/></Suspense>;}
import crosschecks from '../data/crosschecks.json';
import facilityData from '../data/services.json';
import {FacilityControls,FacilityDetails,FacilityList,visibleFacilities} from './Facilities';
import type {Facility,FacilityFilter} from './types';
const facilities=facilityData as Facility[];
import {Modal,NumberField} from './Controls';
import {HazardNotes,HazardTag} from './HealthAdvisories';
import type {Dataset,Place,Route,Selection,Settings,StageId} from './types';
import {budget,candidateTime,clockAt,comparisonCosts,dateAt,dateTime,defaults,duration,itinerary,km,moment,money,overlapping,resolveAdvisories,restore} from './planning';
const storageKey='jedeme-spolu-v1';
const routeStyle=(r:Route)=>({'--route':r.color} as CSSProperties);
const unknown='Aktuální údaj se nepodařilo spolehlivě ověřit.';
const stageLabels=['Do Slovinska','K moři','Domů'];
function External({href,children}:{href:string;children:React.ReactNode}){return <a href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={14}/></a>;}
function PlaceIcon({place}:{place:Place}){return place.category==='food'?<Utensils size={18}/>:place.category==='lake'?<Waves size={18}/>:place.category==='town'?<Compass size={18}/>:<TreePine size={18}/>;}
export default function App(){const [data,setData]=useState<Dataset|null>(null),[error,setError]=useState(false),[retry,setRetry]=useState(0);useEffect(()=>{const controller=new AbortController();setError(false);fetch('/data/trip.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Data');return r.json();}).then((value:Dataset)=>{if(!Array.isArray(value.routes)||!Array.isArray(value.places))throw Error('Data');setData(value);}).catch(e=>{if(e.name!=='AbortError')setError(true);});return()=>controller.abort();},[retry]);return data?<Planner data={data}/>:<main className="loading"><RouteIcon size={40}/><h1>Jedeme spolu</h1><p>{error?'Cestovní data se nepodařilo načíst.':'Připravuji mapu naší cesty…'}</p>{error&&<button onClick={()=>setRetry(n=>n+1)}>Zkusit znovu</button>}</main>;}
function Planner({data}:{data:Dataset}){
 const [excursionFocus,setExcursionFocus]=useState<ExcursionBase|null>(null),[excursionId,setExcursionId]=useState<string|null>(null),[excursionGroup,setExcursionGroup]=useState<string[]|null>(null);
 const [facilityFilter,setFacilityFilter]=useState<FacilityFilter>({toilets:false,fuel:false}),[facilityId,setFacilityId]=useState<string|null>(null),[facilityList,setFacilityList]=useState(false);
 const [facilitySubset,setFacilitySubset]=useState<string[]|null>(null);
 const [settings,setSettings]=useState<Settings>(()=>{try{return restore(localStorage.getItem(storageKey),data);}catch{return defaults(data);}});
 const [stageId,setStageId]=useState<StageId>('si'),[activeId,setActiveId]=useState<string|null>(settings.plan.si?.routeId??null),[overview,setOverview]=useState(false),[placeId,setPlaceId]=useState<string|null>(null),[panel,setPanel]=useState<'settings'|'sources'|'budget'|null>(null),[storageError,setStorageError]=useState(false),[message,setMessage]=useState(''),[view,setView]=useState<'plan'|'summary'>('plan');
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(settings));setStorageError(false);}catch{setStorageError(true);}},[settings]);
 const stage=data.stages.find(s=>s.id===stageId)!;
 const excursionBase:ExcursionBase=stageId==='si'?'si':'hr';
 const localExcursions=useMemo(()=>excursions.filter(p=>p.base===excursionBase),[excursionBase]);
 const mapExcursions=overview?excursions:localExcursions;
 const selectedExcursion=excursions.find(p=>p.id===excursionId);
 function focusExcursions(base:ExcursionBase){setStageId(base);setActiveId(null);setOverview(false);setExcursionFocus(base);}
 const routes=useMemo(()=>data.routes.filter(r=>r.stage===stageId),[data,stageId]);
 const mapRoutes=useMemo(()=>overview?data.routes:routes,[overview,data,routes]);
 const facilityRoutes=activeId?mapRoutes.filter(r=>r.id===activeId):mapRoutes;
 const shownFacilities=visibleFacilities(facilities,facilityRoutes.map(r=>r.id),facilityFilter);
 const selectedFacility=facilities.find(p=>p.id===facilityId);
 const active=data.routes.find(r=>r.id===activeId),selection=settings.plan[stageId];
 const choice=active&&selection?.routeId===active.id?selection:undefined;
 const trip=active?itinerary(active,choice):undefined,price=active?comparisonCosts(data,active,settings,choice):undefined;
 const total=budget(data,settings),departure=settings.departures[stageId];
 const candidateBudget=active?budget(data,{...settings,plan:{...settings.plan,[stageId]:choice??{routeId:active.id,stops:{},reserve:0}}}):null;
 const place=data.places.find(p=>p.id===placeId);
 const placeRoutes=(overview?data.routes:routes).filter(r=>r.stops.some(s=>s.id===placeId));
 const placeRoute=active&&placeRoutes.includes(active)?active:placeRoutes.length===1?placeRoutes[0]:null;
 const viewRoute=useCallback((id:string)=>{const route=data.routes.find(r=>r.id===id);if(route){setStageId(route.stage);setActiveId(id);setOverview(false);setExcursionFocus(null);setMessage('');}},[data]);
 function chooseRoute(route:Route){setSettings(s=>({...s,plan:{...s.plan,[route.stage]:s.plan[route.stage]?.routeId===route.id?s.plan[route.stage]:{routeId:route.id,stops:{},reserve:0}}}));setMessage('Trasa '+route.letter+' je v plánu tohoto dne.');}
 function resetStage(id:StageId){setSettings(s=>{if(!s.plan[id])return s;const plan={...s.plan};delete plan[id];return {...s,plan};});setMessage('Výběr trasy pro '+stageLabels[data.stages.findIndex(s=>s.id===id)]+' je zrušený.');}
 function updateSelection(update:(current:Selection)=>Selection){if(!active)return;setSettings(s=>({...s,plan:{...s.plan,[stageId]:update(s.plan[stageId]?.routeId===active.id?s.plan[stageId]!:{routeId:active.id,stops:{},reserve:0})}}));}
 function addStop(route:Route,p:Place){const existing=settings.plan[route.stage]?.routeId===route.id?settings.plan[route.stage]:undefined;if(existing&&overlapping(route,existing,p.id)){setMessage('Tato zastávka se překrývá s už přidanou zajížďkou. Nejprve odeberte blízkou zastávku, aby se čas nepočítal dvakrát.');return;}setStageId(route.stage);setActiveId(route.id);setSettings(s=>{const current=s.plan[route.stage]?.routeId===route.id?s.plan[route.stage]!:{routeId:route.id,stops:{},reserve:0};return {...s,plan:{...s.plan,[route.stage]:{...current,stops:{...current.stops,[p.id]:p.duration}}}};});setPlaceId(null);setMessage('Zastávka je přidaná. Časy i benzín se přepočítaly.');}
 function changeStage(id:StageId){setView('plan');setStageId(id);setActiveId(settings.plan[id]?.routeId??null);setOverview(false);setExcursionFocus(null);setPlaceId(null);setMessage('');}
 const chosenCount=Object.keys(settings.plan).length;
 return <ExchangeRateContext value={settings.exchangeRate}>
  <header className="header"><a className="brand" href="#top"><RouteIcon size={31}/><span>Jedeme spolu<span className="brand-dot">.</span></span></a><span className="trip-dates">12.–16. září 2026 <span>· 2 dospělí + malý cestovatel</span></span><button className="soft-button" aria-label="Náš rozpočet" onClick={()=>setPanel('budget')}><Wallet size={18}/><span>Náš rozpočet</span>{(chosenCount>0||settings.paidPasses.length>0)&&<b><Money eur={total.total}/></b>}</button></header>
  <main id="top" className="shell">
   <button className="exchange-note" onClick={()=>setPanel('settings')}>Ceny v Kč a € · 1 € = {settings.exchangeRate.toLocaleString('cs-CZ',{maximumFractionDigits:3})} Kč · {settings.exchangeRate===exchange.rate?'ČNB '+dateAt(exchange.date+'T00:00'):'vlastní kurz'}</button>
   <div className="journey-heading"><div><span className="eyebrow">PÁR DNÍ SPOLU. SPOUSTA MOŽNOSTÍ.</span><h1>Nejdřív hory. Potom moře.</h1></div><button className="text-button" onClick={()=>setPanel('settings')}><Settings2 size={17}/> Naše auto a nastavení</button></div>
   <nav className="stages" aria-label="Etapy dovolené">{data.stages.map((s,i)=><button key={s.id} className={'stage '+(s.id===stageId&&view==='plan'?'active':'')} aria-pressed={s.id===stageId&&view==='plan'} onClick={()=>changeStage(s.id)}><span className="stage-date">{s.date.slice(8).replace(/^0/,'')}. 9.</span><span>{stageLabels[i]}</span>{settings.plan[s.id]&&<Check size={15} aria-label="Trasa vybraná"/>}</button>)}<div className="stages-extra"><button className={'overview '+(overview&&view==='plan'?'active':'')} aria-label="Celá dovolená" aria-pressed={overview&&view==='plan'} onClick={()=>{setView('plan');setOverview(v=>!v);setActiveId(null);setExcursionFocus(null);}}><MapIcon size={16}/><span>Celá dovolená</span></button><button className={'summary-tab '+(view==='summary'?'active':'')} aria-label="Souhrn cesty" aria-pressed={view==='summary'} onClick={()=>setView('summary')}><ClipboardList size={16}/><span>Souhrn</span></button></div></nav>
   {view==='summary'?<Summary data={data} settings={settings} total={total} onViewStage={changeStage} onReset={resetStage}/>:
   <div className="workspace">
    <aside className="route-sidebar"><div className="sidebar-title"><span className="eyebrow">{routes.length} VARIANT · VÝBĚR JE NA VÁS</span><h2>{stage.from}<ArrowRight size={18}/><br/>{stage.to}</h2><p>Prohlédněte si cestu. Pak si ji přidejte do plánu.</p></div>
     <div className="route-list">{routes.map(r=>{const c=comparisonCosts(data,r,settings,selection?.routeId===r.id?selection:undefined);return <button key={r.id} className={'route-row '+(activeId===r.id?'active':'')} style={routeStyle(r)} onClick={()=>viewRoute(r.id)} aria-pressed={activeId===r.id}><span className="route-letter">{r.letter}</span><span className="route-copy"><strong>{r.name}</strong><small>{km(r.distanceKm)} km <span>·</span> {duration(r.drivingMinutes)}</small><small>Benzín <Money eur={c.eur}/> · poplatky <Money eur={c.toll+c.passTotal}/></small><span className="row-total"><Money eur={c.total}/> <small>navíc k ostatním etapám</small></span><small>Zatáčky: {r.risk}</small></span>{selection?.routeId===r.id?<Check className="row-arrow" size={17}/>:<ArrowUpRight className="row-arrow" size={17}/>}</button>;})}</div>
     <p className="small-note">Ceny zohledňují ostatní schválené etapy a už zaplacené známky. Částky jednotlivých etap nesčítejte; společné známky přesně rozpočítá Náš rozpočet. Časy jsou bez živé dopravy.</p>
     <button className="source-button" onClick={()=>setPanel('sources')}><Info size={15}/> Zdroje a aktuálnost dat</button>
    </aside>
    <div className="main-column">
     <div className="excursion-map-controls" role="group" aria-label="Zaměření mapy"><button aria-pressed={!excursionFocus} onClick={()=>setExcursionFocus(null)}>Trasy</button><button aria-pressed={excursionFocus==='si'} onClick={()=>focusExcursions('si')}>☀ Výlety · Slovinsko</button><button aria-pressed={excursionFocus==='hr'} onClick={()=>focusExcursions('hr')}>☀ Výlety · Bibinje</button></div>
     <Suspense fallback={<div className="map-wrap loading-map">Načítám mapu…</div>}><MapView excursions={mapExcursions} excursionFocus={excursionFocus} onExcursion={setExcursionId} onExcursionGroup={setExcursionGroup} facilityFilter={facilityFilter} facilities={shownFacilities} onFacility={setFacilityId} onFacilityGroup={ids=>{setFacilitySubset(ids);setFacilityList(true);}} routes={mapRoutes} places={data.places} stage={stage} activeId={activeId} selection={selection} overview={overview} onRoute={viewRoute} onPlace={id=>setPlaceId(id)}/></Suspense>
     <FacilityControls filter={facilityFilter} onChange={setFacilityFilter} count={shownFacilities.length} onList={()=>{setFacilitySubset(null);setFacilityList(true);}}/>
     <div className="map-legend">{routes.map(r=><button style={routeStyle(r)} key={r.id} onClick={()=>viewRoute(r.id)} aria-label={'Zobrazit trasu '+r.letter}><i className={r.dashed?'dashed':''}/>{r.letter}</button>)}{active&&<button className="text-button" onClick={()=>setActiveId(null)}>Všechny stejně výrazné <X size={14}/></button>}<span>♧ příroda &nbsp; ≈ jezero &nbsp; ⌂ město &nbsp; ♨ jídlo</span></div>
     <section className="day-plan" aria-labelledby="day-title"><div className="section-heading"><div><span className="eyebrow">{dateAt(departure)} · {stage.title}</span><h2 id="day-title">Jak může vypadat náš den</h2></div><span className="pill">{active?'Prohlížíte '+active.letter:'Zatím bez vybrané cesty'}</span></div>
      <div className="plan-intro"><label className="departure">Odjezd · {stage.from}<input type="time" value={departure.slice(11,16)} required onInput={e=>{const value=e.currentTarget.value;if(/^\d{2}:\d{2}$/.test(value))setSettings(s=>({...s,departures:{...s.departures,[stageId]:stage.date+'T'+value}}));}} onChange={e=>{if(/^\d{2}:\d{2}$/.test(e.target.value))setSettings(s=>({...s,departures:{...s.departures,[stageId]:stage.date+'T'+e.target.value}}));}}/></label><p>{stage.note}</p></div>
      {!active?<div className="empty-plan"><RouteIcon size={30}/><div><h3>Každá cesta má svůj příběh.</h3><p>Klikněte na barevnou cestu v mapě nebo na její písmeno. Tady pak uvidíte časy, zastávky a možnosti výletu.</p></div></div>:<>
       <div className="route-detail-heading" style={routeStyle(active)}><span className="route-letter">{active.letter}</span><div><h3>{active.name}</h3><p>{active.via}</p></div><button className={choice?'soft-button':'primary'} onClick={()=>chooseRoute(active)}>{choice?<Check size={17}/>:<Plus size={17}/>} {choice?'V našem plánu':'Použít pro tento den'}</button></div>
       {choice&&<button className="text-button" onClick={()=>resetStage(stageId)}><RotateCcw size={15}/> Zrušit výběr trasy pro tento den</button>}
       <div className="metrics"><div><span>Čistá jízda</span><strong>{duration(active.drivingMinutes)}</strong><small>{km(active.distanceKm)} km bez zajížděk</small></div><div><span>S rodinnými pauzami</span><strong>{duration(Math.ceil((active.drivingMinutes+Math.floor(active.drivingMinutes/120)*20)/10)*10)} – {duration(Math.ceil((active.drivingMinutes+Math.floor(active.drivingMinutes/120)*35+30)/10)*10)}</strong><small>Odhad: 20–35 min po cca 2 h + až 30 min rezerva</small></div><div><span>Benzín + silniční poplatky</span><strong><Money eur={price!.total}/></strong><small>Navíc k ostatním etapám · platné známky zohledněny</small></div></div>
       {candidateBudget&&!choice&&<p className="small-note">{selection?'Změna rozpočtu při nahrazení současné trasy':'Nový výdaj při přidání do plánu'}: <strong><Money eur={candidateBudget.total-total.total}/></strong>. Celý plán by stál <Money eur={candidateBudget.total}/>. Platné známky se sdílí mezi etapami.</p>}
       <div className="plan-grid"><div className="timeline">
        <div className="event"><time>{clockAt(departure)}</time><div><h3>Vyjíždíme · {stage.from}</h3><p>{dateAt(departure)} · čas si upravíte výše</p></div></div>
        {trip!.stops.map(s=>{const p=data.places.find(x=>x.id===s.visit.id)!;return <div className="event" key={p.id}><time>{clockAt(departure,s.arrivalMinute)}<small>{dateAt(departure,s.arrivalMinute)}</small></time><div><button className="event-name" onClick={()=>setPlaceId(p.id)}>{p.name}<ArrowUpRight size={14}/></button><p>{km(s.distanceKm)} km od startu · zajížďka +{Math.round(s.visit.detourMinutes)} min</p><div className="event-controls"><NumberField label="Pobyt (min)" value={s.duration} min={5} max={360} onChange={n=>updateSelection(c=>({...c,stops:{...c.stops,[p.id]:n}}))}/><button className="icon-button" aria-label={'Odebrat '+p.name} onClick={()=>updateSelection(c=>{const stops={...c.stops};delete stops[p.id];return {...c,stops};})}><Trash2 size={17}/></button></div><p>Odjezd {clockAt(departure,s.leaveMinute)}</p></div></div>;})}
        {!trip!.stops.length&&<div className="event"><time>Cestou</time><div><h3>Místo pro příjemnou pauzu</h3><p>Níže vyberte zastávky. Zatím se do příjezdu žádná pauza nezapočítává.</p></div></div>}
        <div className="event arrival"><time>{clockAt(departure,trip!.minutes)}<small>{dateAt(departure,trip!.minutes)}</small></time><div><h3>Příjezd · {stage.to}</h3><p>Podle aktuálního itineráře: {duration(trip!.minutes)} včetně {trip!.pauseMinutes} min pobytu, {Math.round(trip!.detourMinutes)} min zajížděk a {trip!.reserve} min rezervy.</p>{stage.checkIn&&<p className="checkin">{moment(departure,trip!.minutes).epochMilliseconds<moment(stage.checkIn).epochMilliseconds?`Do check-inu od 14:00 zbývá přibližně ${Math.round((moment(stage.checkIn).epochMilliseconds-moment(departure,trip!.minutes).epochMilliseconds)/60000)} min.`:'Ubytování je dostupné od '+dateTime(stage.checkIn)+'.'}</p>}</div></div>
        {choice&&<NumberField label="Vlastní časová rezerva (min)" value={choice.reserve} min={0} max={360} onChange={n=>updateSelection(c=>({...c,reserve:n}))}/>}<p className="small-note">Rezerva je přidaná k cílovému příjezdu. Místo protažení vybírejte podle únavy; uvedené tipy nemusí vyplnit každý dvouhodinový úsek.</p>
       </div><div className="stops-list"><h3>Malá odbočka, hezčí den.</h3><p>Tipy na této cestě. Přidávejte jen ty, na které máte chuť a čas.</p>{active.stops.map(s=>{const p=data.places.find(x=>x.id===s.id)!;return <button key={s.id} className="stop-card" onClick={()=>setPlaceId(s.id)}><StopPhoto id={p.id}/><span><strong>{p.name}</strong><small>{choice?.stops[s.id]??p.duration} min pobyt · +{Math.round(s.detourMinutes)} min jízdy</small><small>Příjezd v plánu {clockAt(departure,candidateTime(active,s.id,choice))}</small><HazardTag advisories={resolveAdvisories(data.healthAdvisories,p.healthAdvisories)}/></span>{choice?.stops[s.id]!==undefined?<Check size={16}/>:<Plus size={16}/>}</button>;})}</div></div>
       <RoadbookPanel data={data} route={active} settings={settings} selection={choice}/><RouteDetails route={active} settings={settings} selection={choice} data={data}/>
      </>}
     </section>
     <ExcursionSection places={localExcursions} base={excursionBase} onPlace={setExcursionId} onFocus={()=>focusExcursions(excursionBase)}/>
    </div>
   </div>}
   <footer><span>Plán pro nás. Rozhodnutí na cestě je naše.</span><button onClick={()=>setPanel('sources')}>Ceny 8. 9. · adresa Bibinje 9. 9. 2026 <Info size={14}/></button><span>Časová zóna Europe/Prague</span></footer>
  </main>
  {(message||storageError)&&<div className="toast" role="status"><span>{storageError?'Plán se nedaří uložit v tomto prohlížeči. Změny platí do zavření stránky.':message}</span><button aria-label="Skrýt zprávu" onClick={()=>setMessage('')}><X size={17}/></button></div>}
  {panel==='settings'&&<Modal title="Naše auto a nastavení" onClose={()=>setPanel(null)}><p>Škoda Superb · osobní auto bez přívěsu. Českou známku už máte; nový výdaj je <Money eur={0}/>.</p><div className="form-grid"><NumberField label="Spotřeba (l / 100 km)" value={settings.consumption} min={2} max={30} step={.1} onChange={n=>setSettings(s=>({...s,consumption:n}))}/><NumberField label="Cena benzínu (€ / l)" value={settings.fuelPrice} min={.1} max={10} step={.001} onChange={n=>setSettings(s=>({...s,fuelPrice:n}))}/></div><p>Vaše cena benzínu: <Money eur={settings.fuelPrice} digits={3} unit="/l"/></p><NumberField label="Kurz (Kč za 1 €)" value={settings.exchangeRate} min={1} max={100} step={.001} onChange={n=>setSettings(s=>({...s,exchangeRate:n}))}/><p className="small-note">Výchozí kurz ČNB k {dateAt(exchange.date+'T00:00')}: 1 € = {exchange.rate.toLocaleString('cs-CZ')} Kč. Koruny jsou orientační přepočet; banka může použít jiný kurz.</p><button className="text-button" onClick={()=>setSettings(s=>({...s,exchangeRate:exchange.rate}))}>Obnovit kurz ČNB</button><External href={exchange.source}>Zdroj kurzu ČNB</External><p>Výchozí cena <Money eur={1.912} digits={3} unit="/l"/>: rakouský průměr Eurosuper 95 včetně daní, WKO, údaj k 7. 9. 2026; ověřeno 8. 9. 2026. Ve všech trasách používáme stejnou cenu.</p><p className="formula">Benzín = (km ÷ 100) × spotřeba × cena za litr</p><External href={data.sources.find(s=>s.id==='fuel')!.url}>Zdroj ceny benzínu</External><p className="small-note">Plán se ukládá pouze do tohoto prohlížeče. Na jiném telefonu se automaticky neobjeví.</p></Modal>}
  {panel==='sources'&&<Sources data={data} onClose={()=>setPanel(null)}/>}
  {selectedExcursion&&<ExcursionDetails place={selectedExcursion} settings={settings} onClose={()=>setExcursionId(null)}/>}
  {excursionGroup&&<Modal title="Výlety v tomto okolí" onClose={()=>setExcursionGroup(null)}><p>Klikněte na výlet pro fotografii, dojezd a praktické informace.</p><ExcursionCards places={excursions.filter(p=>excursionGroup.includes(p.id))} onPlace={id=>{setExcursionGroup(null);setExcursionId(id);}}/></Modal>}
  {panel==='budget'&&<Modal title="Náš rozpočet na cestu" onClose={()=>setPanel(null)}><p>{chosenCount} ze 3 etap má zvolenou trasu. Částky zahrnují zvolené zajížďky v benzínu.</p><Suspense fallback={<p>Načítám stažení…</p>}><TripDownload data={data} settings={settings}/></Suspense>
  <div className="budget-total"><Money eur={total.total}/><small>{chosenCount===3?'Benzín + silniční poplatky':'Průběžný součet vybraných etap'}</small></div>{data.stages.map(s=>{const c=settings.plan[s.id],r=data.routes.find(x=>x.id===c?.routeId);return <div className="budget-line" key={s.id}><span>{s.from} → {s.to}<small>{r?r.letter+' · '+r.name:'Trasu jste ještě nevybrali'}</small></span>{r&&<button className="icon-button" aria-label={'Odebrat etapu '+s.to} onClick={()=>setSettings(v=>{const plan={...v.plan};delete plan[s.id];return {...v,plan};})}><Trash2 size={17}/></button>}</div>;})}<p>Už zaplacené zahraniční známky: <strong><Money eur={total.paidTotal}/></strong><br/>Odhad zbývajících výdajů za cestu: <strong><Money eur={total.remaining}/></strong></p><dl className="cost-list"><div><dt>Benzín · {km(total.distanceKm)} km</dt><dd><Money eur={total.gas}/></dd></div><div><dt>Úsekové a chorvatské mýto</dt><dd><Money eur={total.toll}/></dd></div>{total.passes.map((p,i)=><div key={i}><dt>{p.name}<small>Ještě ke koupi · {dateAt(p.from+'T00:00')} – {dateAt(p.to+'T00:00')} včetně</small></dt><dd><Money eur={p.eur}/></dd></div>)}</dl><p className="note">Platné známky se neopakují za každou etapu. U zastávek Ogulin a Fužine se zohlední rozdělení mýta při sjezdu z dálnice. Jídlo, parkování, vstupné a výlety od ubytování nejsou zahrnuté. Zapsané nákupy známek zůstávají v celkovém rozpočtu i po změně trasy.</p><PaidPasses paid={settings.paidPasses} planned={total.passes} onChange={paidPasses=>setSettings(s=>({...s,paidPasses}))}/></Modal>}
  {facilityList&&<FacilityList facilities={facilitySubset?shownFacilities.filter(p=>facilitySubset.includes(p.id)):shownFacilities} routes={facilityRoutes} onPlace={id=>{setFacilityList(false);setFacilityId(id);}} onClose={()=>setFacilityList(false)}/>}
  {selectedFacility&&<FacilityDetails facility={selectedFacility} routes={facilityRoutes} onClose={()=>setFacilityId(null)}/>}
  {place&&<Modal title={place.name} onClose={()=>setPlaceId(null)}>{!placeRoute?<><StopPhoto id={place.id} detail/><p>Místo leží u více tras. Vyberte, pro kterou chcete zobrazit příjezd:</p>{placeRoutes.map(r=><button key={r.id} className="choice-button" onClick={()=>{setStageId(r.stage);setActiveId(r.id);setOverview(false);}} style={routeStyle(r)}><span className="route-letter">{r.letter}</span>{r.name} · {r.stage==='si'?'12. 9.':r.stage==='hr'?'13. 9.':'16. 9.'}<ArrowRight size={17}/></button>)}</>:<StopDetails place={place} route={placeRoute} data={data} settings={settings} onAdd={()=>addStop(placeRoute,place)} onRemove={()=>{const id=place.id;setSettings(s=>{const c=s.plan[placeRoute.stage];if(!c)return s;const stops={...c.stops};delete stops[id];return {...s,plan:{...s.plan,[placeRoute.stage]:{...c,stops}}};});setPlaceId(null);}}/>}</Modal>}
 </ExchangeRateContext>;
}
function Summary({data,settings,total,onViewStage,onReset}:{data:Dataset;settings:Settings;total:ReturnType<typeof budget>;onViewStage:(id:StageId)=>void;onReset:(id:StageId)=>void}){
 const chosenCount=Object.keys(settings.plan).length;
 return <section className="summary-view" aria-labelledby="summary-title">
  <Suspense fallback={<p>Načítám stažení…</p>}><TripDownload data={data} settings={settings}/></Suspense>
  <div className="section-heading"><div><span className="eyebrow">CELÁ DOVOLENÁ NA JEDNOM MÍSTĚ</span><h2 id="summary-title">Souhrn cesty</h2></div></div>
  <p className="small-note">Přehled zvolených tras, časů a cen i bez mapy — pro případ, že by cestou vypadla navigace. Ceny zohledňují sdílené dálniční známky mezi etapami; přesný společný rozpočet najdete v Náš rozpočet.</p>
  <div className="budget-total"><Money eur={total.total}/><small>{chosenCount===3?'Benzín + silniční poplatky za celou cestu':'Průběžný součet vybraných etap'}</small></div>
  {data.stages.map((stage,i)=>{
   const choice=settings.plan[stage.id];
   const route=choice&&data.routes.find(r=>r.id===choice.routeId&&r.stage===stage.id);
   const departure=settings.departures[stage.id];
   if(!route)return <article className="summary-stage" key={stage.id}>
    <h3>{dateAt(stage.date+'T00:00')} · {stageLabels[i]}</h3>
    <p className="summary-route-from">{stage.from} <ArrowRight size={14}/> {stage.to}</p>
    <p className="small-note">Trasu jste pro tento den ještě nevybrali.</p>
    <button className="text-button" onClick={()=>onViewStage(stage.id)}>Vybrat trasu <ArrowRight size={15}/></button>
   </article>;
   const trip=itinerary(route,choice),price=comparisonCosts(data,route,settings,choice);
   return <article className="summary-stage" key={stage.id} style={routeStyle(route)}>
    <h3>{dateAt(stage.date+'T00:00')} · {stageLabels[i]}</h3>
    <p className="summary-route-from">{stage.from} <ArrowRight size={14}/> {stage.to}</p>
    <div className="summary-route-name"><span className="route-letter">{route.letter}</span><span><strong>{route.name}</strong><small>{route.via}</small></span></div>
    <p className="small-note">{km(trip.distanceKm)} km · {duration(trip.minutes)} s vybranými pauzami{trip.reserve?' a rezervou':''}.</p>
    <ul className="summary-timeline">
     <li><time>{clockAt(departure)}</time><span>Odjezd · {stage.from}</span></li>
     {trip.stops.map(s=>{const p=data.places.find(x=>x.id===s.visit.id)!;return <li key={p.id}><time>{clockAt(departure,s.arrivalMinute)}</time><span>{p.name} <small>· {s.duration} min</small></span></li>;})}
     <li><time>{clockAt(departure,trip.minutes)}</time><span>Příjezd · {stage.to}</span></li>
    </ul>
    <p className="summary-price">Benzín + poplatky <strong><Money eur={price.total}/></strong><small>navíc k ostatním etapám</small></p>
    <RoadbookPanel data={data} route={route} settings={settings} selection={choice}/><div className="summary-actions"><button className="text-button" onClick={()=>onViewStage(stage.id)}>Zobrazit na mapě <ArrowRight size={15}/></button><button className="text-button" onClick={()=>onReset(stage.id)}><RotateCcw size={15}/> Zrušit výběr</button></div>
   </article>;
  })}
 </section>;
}
function RouteDetails({route,settings,selection,data}:{route:Route;settings:Settings;selection?:Selection;data:Dataset}){const c=comparisonCosts(data,route,settings,selection),t=itinerary(route,selection);return <div className="route-facts">
 <details open><summary>Silnice, zatáčky a pohoda za volantem <ChevronDown size={17}/></summary><div className="fact-grid"><div><h4>Zatáčky: {route.risk}</h4><p>{route.roads}</p><p>Přibližně {km(route.highwayKm)} km v dálničních úsecích a {km(route.distanceKm-route.highwayKm)} km mimo ně. Jde o odhad ze skupin navigačních pokynů, ne přesné zaměření každého kilometru.</p><h4>Náročnost pro řidiče</h4><p>{route.driverEffort}</p></div><div><h4>Co uvidíme</h4><p>{route.scenery}</p><h4>Pro tuto cestu</h4>{route.pros.map(p=><p key={p} className="pro">+ {p}</p>)}<h4>Co mluví proti</h4>{route.cons.map(p=><p key={p}>− {p}</p>)}</div></div><p className="small-note">Praktické srovnání citlivosti na zatáčky podle typu silnic, nikoli zdravotní hodnocení. Nižší riziko neznamená cestu bez zatáček.</p>{route.id==='si-c'&&<div className="note"><b>Ljubelj bez slovinské dálniční známky</b><p>Uložený jižní úsek byl vypočten s vyloučením dálnic a mýta; routing potvrzuje obojí bez použití. Trasa vede tunelem Ljubelj, nikoli starou cestou přes vrchol sedla. Budoucí průjezdnost a uzavírky: {unknown}</p><p>Tscheppaschlucht jsme prověřili: 1,5–3 h samotné chůze, lávky a přes 300 schodů. S dítětem to není 20minutová pauza; proto není mezi krátkými zastávkami. Dospělý <Money eur={12.5}/>, parkování <Money eur={6}/>, tarif pětiletého dítěte nepotvrzen. <External href="https://www.tscheppaschlucht-ferlach.at/">Podrobnosti soutěsky</External></p></div>}{route.stage==='si'&&<p className="small-note">Posledních přibližně 500 m k zadanému GPS ubytování má v mapových datech příznak horšího povrchu. Přesný příjezd ověřte s ubytovatelem.</p>}{route.stage==='home'&&route.id!=='home-c'&&<p className="note">Na A2 Zagreb–Macelj jsou oznámené zářijové práce. Při pozdním průjezdu 16. 9. zkontrolujte i noční omezení. <External href="https://www.azm.hr/">Aktuální provoz AZM</External></p>}</details>
 <details><summary>Benzín, známky a mýto <ChevronDown size={17}/></summary><p>Ověřeno k 8. 9. 2026. Osobní auto bez přívěsu: AT do 3,5 t, SI 2A, HR I. Konečné tarify ověřte před nákupem.</p><h4>Společné časové známky</h4><p>Česká známka: už zakoupená, nově <Money eur={0}/>. Rakouská nebo slovinská se v celém plánu znovu neúčtuje, pokud ještě platí.</p><dl className="cost-list">{c.passCharges.map(p=><div key={p.country}><dt>{p.country==='AT'?'Rakouská známka':'Slovinská známka 2A'}<small>{p.paid?'Už zaplaceno · platí pro tento průjezd':p.shared?'Zahrnuto v ostatních schválených etapách':'Nová známka nebo změna dosud nekoupeného plánu'}</small>{!p.paid&&settings.paidPasses.some(v=>v.country===p.country)&&<small>Zapsaná známka nepokrývá celou dobu průjezdu.</small>}{p.passes.map(v=><small key={v.from+v.to}>{dateAt(v.from+'T00:00')} – {dateAt(v.to+'T00:00')} včetně</small>)}</dt><dd><Money eur={p.eur}/></dd></div>)}</dl><p className="small-note">U nekoupených známek se může změnit plánovaný typ i cena, například z jednodenní na desetidenní. Už koupenou známku nepovažujeme za vyměnitelnou ani vratnou. Úsekové mýto se platí za každý průjezd.</p>{!route.vignettes.includes('SI')&&<p>V této etapě slovinská známka není potřeba. Pro další den už ji můžete potřebovat.</p>}<h4>Poplatky specifické pro tuto trasu</h4><dl className="cost-list">{route.tolls.length?route.tolls.map(p=><div key={p.name}><dt><External href={data.sources.find(s=>s.id===p.source)!.url}>{p.name}</External></dt><dd><Money eur={p.eur}/></dd></div>):<p>Žádné další úsekové mýto na základní trase.</p>}{route.tollAdjustments?.filter(a=>selection?.stops[a.stopId]!==undefined).map(a=><div key={a.stopId}><dt><External href={data.sources.find(s=>s.id===a.source)!.url}>Úprava po sjezdu: {data.places.find(p=>p.id===a.stopId)?.name}</External></dt><dd><Money eur={a.eur}/></dd></div>)}<div><dt>Nové poplatky této varianty oproti ostatním etapám</dt><dd><Money eur={c.toll+c.passTotal}/></dd></div><div><dt>Benzín · {c.liters.toFixed(1).replace('.',',')} l</dt><dd><Money eur={c.eur}/></dd></div><div className="strong"><dt>Benzín + poplatky</dt><dd><Money eur={c.total}/></dd></div></dl><p className="formula">({km(t.distanceKm)} km ÷ 100) × {settings.consumption} l × <Money eur={settings.fuelPrice} digits={3} unit="/l"/><br/><small>Výpočet používá nezaokrouhlenou vzdálenost včetně vybraných zajížděk.</small></p><p className="small-note">Částka zahrnuje i úpravu mýta za zvolené sjezdy v Ogulinu a Fužine. Jídlo, vstupné ani parkování nejsou v součtu.</p></details>
 <details><summary>Jak vznikly údaje a ověření provozu <ChevronDown size={17}/></summary><p>Skutečná silniční geometrie z Valhalla / OpenStreetMap, výpočet k {dateAt(route.checkedAt.slice(0,10)+'T00:00')}. Základní jízdní čas neobsahuje živou dopravu, čekání na hranicích nebo fronty u mýta. Zaokrouhlení v přehledu není příslib přesného příjezdu.</p><p>Zajížďky nahrazují úsek základní trasy mezi dvěma body v okolí zastávky. Jejich čas a kilometry se přičítají; blízké překrývající se zajížďky nelze přidat současně. Zahrnut je silniční příjezd, hledání parkování patří do pobytu nebo vlastní rezervy.</p>{route.routingUrls.map((url,i)=><p key={i}><External href={url}>Přesný routingový dotaz {i+1}</External></p>)}<External href={'/data/'+route.id+'.geojson'}>Uložená geometrie GeoJSON</External><p><External href="https://www.promet.si/">Aktuální provoz ve Slovinsku</External></p><p><External href="https://www.asfinag.at/verkehr-sicherheit/verkehrsinfos/">Aktuální provoz v Rakousku</External></p><p><External href="https://www.hac.hr/hr/servisne-informacije/stanje-na-autocestama">Aktuální provoz v Chorvatsku</External></p></details>
 </div>;}
function StopDetails({place,route,data,settings,onAdd,onRemove}:{place:Place;route:Route;data:Dataset;settings:Settings;onAdd:()=>void;onRemove:()=>void}){const visit=route.stops.find(s=>s.id===place.id)!,selection=settings.plan[route.stage]?.routeId===route.id?settings.plan[route.stage]:undefined;const eta=candidateTime(route,place.id,selection),departure=settings.departures[route.stage],stay=selection?.stops[place.id]??place.duration;const arrival=moment(departure,eta);const hour=arrival.hour+arrival.minute/60;const hoursWarning=place.hours&&(hour<place.hours[0]||hour+stay/60>place.hours[1]);const dayWarning=place.id==='friesach'&&(arrival.dayOfWeek===7||arrival.dayOfWeek===1);return <>
 <StopPhoto id={place.id} detail/><span className="pill">Varianta {route.letter} · {route.name}</span><HazardNotes advisories={resolveAdvisories(data.healthAdvisories,place.healthAdvisories)}/><p className="lead">{place.description}</p>
 <div className="stop-times"><div><small>ETA bez předchozích pauz a zajížděk</small><strong>{dateTime(departure,visit.atMinute)}</strong></div><div><small>ETA podle aktuálního itineráře</small><strong>{dateTime(departure,eta)}</strong></div></div>
 <p>{km(visit.atKm)} km po příjezdu základním koridorem od startu etapy · čistá jízda k místu {duration(visit.atMinute)}. Předchozí vybrané pauzy posouvají druhý čas.</p>
 <div className="fact-grid"><div><h4>Doporučený pobyt</h4><p>{place.duration} minut (náš odhad včetně krátké chůze).</p><h4>Zajížďka autem</h4><p>+{visit.detourKm.toFixed(1).replace('.',',')} km · +{Math.round(visit.detourMinutes)} min proti základní trase.</p></div><div><h4>Co by se mohlo líbit dítěti</h4><p>{place.childAppeal}</p><h4>A dospělým</h4><p>{place.adultAppeal}</p></div></div>
 <h4>Otevírací doba</h4><p>{place.openingHours}</p>{(hoursWarning||dayWarning)&&<p className="note">Pozor: vypočtený čas nebo délka pobytu neodpovídá uvedené otevírací době. Změňte plán nebo si provoz předem ověřte.</p>}{hour<7&&<p className="note">Příjezd vychází velmi brzy. Počítejte s možnou tmou a zavřenou gastronomií.</p>}
 <h4>Vstupné a parkování</h4><p><CurrencyText text={place.cost}/></p>{place.cost!==unknown&&<p className="small-note">Ověřeno k 8. 9. 2026. Pokud parkovné není uvedené, {unknown.toLowerCase()}</p>}
 <div className="fact-grid"><div><h4>Toalety</h4><p>{place.toilets}</p></div><div><h4>Jídlo / káva</h4><p>{place.food}</p></div></div><h4>Co zvážit</h4>{place.risks.map(r=><p key={r}>• {r}</p>)}<p className="small-note">Bod označuje mapový přístup k místu, nikoli garantované volné parkoviště. Režim vjezdu a poslední pěší úsek ověřte na místě. Silniční výpočet a polohová data: 8.–9. 9. 2026.</p>
 <div className="source-links">{place.sources.map(id=>{const source=data.sources.find(s=>s.id===id)!;return <External key={id} href={source.url}>{source.title}</External>;})}<External href={'https://www.google.com/maps/search/?api=1&query='+visit.coordinates[1]+','+visit.coordinates[0]}>Otevřít místo v Google Maps</External><External href={visit.routingUrl}>Ověřit výpočet příjezdu</External></div>
 <div className="sticky-action">{selection?.stops[place.id]!==undefined?<button className="soft-button" onClick={onRemove}><Trash2 size={17}/> Odebrat z cesty</button>:<button className="primary" onClick={onAdd}><Plus size={18}/> Přidat do cesty · {place.duration} min</button>}<small>Přidání použije trasu {route.letter} pro tento den.</small></div>
 </>;}
function Sources({data,onClose}:{data:Dataset;onClose:()=>void}){return <Modal title="Zdroje a aktuálnost dat" onClose={onClose}><p>Ceny byly ověřovány 8. 9. 2026, geometrie 8.–9. 9. 2026. Podkladová mapa potřebuje internet; směrování a výpočty cest používají uložená data. Nejde o živou dopravní prognózu.</p><p>Počítáme s osobním Superbem bez přívěsu, 2 dospělými a dítětem 5 let. Spotřebu a cenu benzínu můžete změnit. Cíl v Bibinje je nově Branimirova obala 12. Bod ubytování Apartman More pochází z katalogu Travelmyth; konkrétní vjezd a parkování ještě potvrďte s hostitelem.</p><p>Hodnocení zatáček, scenérie, vhodnosti pauz a doporučené délky pobytu jsou naše odhady. Nepotvrzené ceny, otevírací doby nebo vybavení jsou označené přímo u místa.</p><h4>Kontrola druhým výpočtem</h4><p>OSRM se stejnými průjezdními body vrací téměř stejnou délku, ale jiný rychlostní profil. V aplikaci používáme souvisle Valhallu; rozdíly neinterpretujeme jako živou dopravu.</p>{crosschecks.map(c=><p key={c.id}><External href={c.url}>{data.routes.find(r=>r.id===c.id)?.name}</External>: Valhalla {km(c.primaryKm)} km / {duration(c.primaryMinutes)}, OSRM {km(c.distanceKm)} km / {duration(c.drivingMinutes)}.</p>)}{data.sources.map(s=><article className="source-item" key={s.id}><External href={s.url}>{s.title}</External><small>Ověřeno k {dateAt(s.checkedAt+'T00:00')}</small><p><CurrencyText text={s.note}/></p></article>)}</Modal>;}
