import {ArrowUpRight,Car,Sun} from 'lucide-react';
import {Modal} from './Controls';
import {StopPhoto} from './StopPhoto';
import {Money,CurrencyText} from './Money';
import {baseNames} from './excursionData';
import {dateAt,fuel} from './planning';
import type {Excursion,ExcursionBase,Settings} from './types';

const km=(n:number)=>n.toLocaleString('cs-CZ',{maximumFractionDigits:1});
export function ExcursionCards({places,onPlace}:{places:Excursion[];onPlace:(id:string)=>void}){
 return <div className="excursion-cards">{places.map(p=><button className="stop-card" key={p.id} onClick={()=>onPlace(p.id)}><StopPhoto id={p.photoId}/><span><strong>{p.name}</strong><small><Car size={12}/> {Math.ceil(p.drive.drivingMinutes)} min · {km(p.drive.distanceKm)} km od ubytování</small><small>{p.duration}{p.drive.paidAlternative?' · placená dálnice':''}</small></span><ArrowUpRight size={16}/></button>)}</div>;
}
export function ExcursionSection({places,base,onPlace,onFocus}:{places:Excursion[];base:ExcursionBase;onPlace:(id:string)=>void;onFocus:()=>void}){
 return <section className="excursion-section" aria-labelledby="excursion-title"><div className="section-heading"><div><span className="eyebrow">{base==='si'?'12.–13. září · pod Alpami':'13.–16. září · u moře'}</span><h2 id="excursion-title">Až budeme na místě.</h2></div><button className="text-button" onClick={onFocus}><Sun size={17}/> Přiblížit výlety</button></div><p>{places.length} tipů do hodiny autem od {baseNames[base]}. Klikněte na fotku nebo na sluníčko v mapě.</p><p className="small-note">Jízdní čas je jedním směrem, bez živé dopravy a hledání parkování. Chůze, lanovky a čas na místě jsou navíc. Tyto výlety se nepřidávají do přejezdového itineráře.</p><ExcursionCards places={places} onPlace={onPlace}/></section>;
}
export function ExcursionDetails({place,settings,onClose}:{place:Excursion;settings:Settings;onClose:()=>void}){
 const d=place.drive,gas=fuel(d.distanceKm+d.returnKm,settings.consumption,settings.fuelPrice);
 const navigation='https://www.google.com/maps/dir/?api=1&origin='+d.origin[1]+','+d.origin[0]+'&destination='+d.accessCoordinates[1]+','+d.accessCoordinates[0]+'&travelmode=driving';
 return <Modal title={place.name} onClose={onClose}><StopPhoto id={place.photoId} detail/><span className="pill">Výlet od ubytování · {place.base==='si'?'Slovinsko':'Bibinje'}</span><p className="lead">{place.description}</p><div className="stop-times"><div><small>Autem tam · {km(d.distanceKm)} km</small><strong>{Math.ceil(d.drivingMinutes)} minut</strong></div><div><small>Autem zpět · {km(d.returnKm)} km</small><strong>{Math.ceil(d.returnMinutes)} minut</strong></div></div><p className="small-note">Výchozí bod: {baseNames[place.base]}. Jedná se o silniční příjezd k parkovišti nebo nástupnímu bodu; další chůze a čekání nejsou v čase autem. Provoz může cestu prodloužit nad hodinu.</p><h4>Jak si výlet užít</h4><p>{place.tip}</p><div className="fact-grid"><div><h4>Čas na výlet</h4><p>{place.duration}</p><h4>Chůze a náročnost</h4><p>{place.walking}</p><p>{place.difficulty}</p><h4>S pětiletým cestovatelem</h4><p>{place.family}</p></div><div><h4>Otevírací doba</h4><p>{place.openingHours}</p><h4>Vstupné</h4><p><CurrencyText text={place.cost}/></p><h4>Parkování a poslední úsek</h4><p>{place.parking}</p></div></div><h4>Benzín tam i zpět</h4><p><Money eur={gas.eur}/> za {km(d.distanceKm+d.returnKm)} km podle vašeho nastavení auta. Vstupné, parkování a případné mýto jsou navíc.</p>{d.paidAlternative?<p className="note">Do hodiny se tato varianta vejde s využitím placené dálnice. {place.base==='hr'?<>Mýto není v ceně benzínu; konkrétní částku ověřte podle nájezdu a výjezdu v <a href="https://www.hac.hr/en/toll/toll-rates" target="_blank" rel="noopener noreferrer">ceníku HAC</a>.</>:<>Je potřeba platná slovinská dálniční známka. Pokud už ji máte, znovu ji nekupujete.</>}</p>:<p className="small-note">Uložený příjezd byl vypočten s vyloučením placených úseků a trajektů.</p>}<div className="fact-grid"><div><h4>Toalety</h4><p>{place.toilets}</p></div><div><h4>Jídlo a pití</h4><p>{place.food}</p></div></div><h4>Co zvážit</h4><ul className="excursion-risks">{place.risks.map(r=><li key={r}>{r}</li>)}</ul><p className="small-note">Obsah ověřen {dateAt(place.checkedAt+'T00:00')}, silniční výpočet {dateAt(d.checkedAt.slice(0,10)+'T00:00')}. Délky procházek a doporučený pobyt jsou naše odhady. Fotografie mohou zachycovat jiné roční období.</p><div className="source-links">{place.sources.map(s=><a href={s.url} key={s.url} target="_blank" rel="noopener noreferrer">{s.title} <ArrowUpRight size={14}/></a>)}<a href={d.positionUrl} target="_blank" rel="noopener noreferrer">Zdroj příjezdového bodu <ArrowUpRight size={14}/></a><a href={d.routingUrl} target="_blank" rel="noopener noreferrer">Ověřit silniční výpočet <ArrowUpRight size={14}/></a></div><div className="sticky-action"><a className="primary" href={navigation} target="_blank" rel="noopener noreferrer">Navigovat od ubytování <ArrowUpRight size={17}/></a><small>Google Maps může nabídnout jinou trasu; zkontrolujte poplatky a aktuální provoz.</small></div></Modal>;
}
