import {Fuel,Toilet,ArrowUpRight,List} from 'lucide-react';
import {Modal} from './Controls';
import type {Facility,FacilityFilter,Route} from './types';
import {dateAt,km} from './planning';

export function visibleFacilities(facilities:Facility[],routeIds:string[],filter:FacilityFilter){
 const order=(p:Facility)=>Math.min(...p.visits.filter(v=>routeIds.includes(v.routeId)).map(v=>routeIds.indexOf(v.routeId)*10000+v.atKm));
 return facilities.filter(p=>((filter.toilets&&p.toilets)||(filter.fuel&&p.fuel.length>0))&&p.visits.some(v=>routeIds.includes(v.routeId))).sort((a,b)=>order(a)-order(b));
}
export function FacilityControls({filter,onChange,count,onList}:{filter:FacilityFilter;onChange:(value:FacilityFilter)=>void;count:number;onList:()=>void}){
 return <div className="facility-controls" role="group" aria-label="Praktické zastávky v mapě"><span>Po cestě</span><button aria-pressed={filter.toilets} onClick={()=>onChange({...filter,toilets:!filter.toilets})}><Toilet size={17}/> WC</button><button aria-pressed={filter.fuel} onClick={()=>onChange({...filter,fuel:!filter.fuel})}><Fuel size={17}/> Benzín</button><button className="facility-list-button" onClick={onList}><List size={17}/>{count} míst</button></div>;
}
export function FacilityList({facilities,routes,onPlace,onClose}:{facilities:Facility[];routes:Route[];onPlace:(id:string)=>void;onClose:()=>void}){
 return <Modal title="WC a benzín po cestě" onClose={onClose}><p>Místa odpovídají právě zobrazené trase a zapnutým filtrům. Klikněte pro podrobnosti a příjezd.</p>{!facilities.length&&<p>Pro toto zobrazení nejsou zapnutá žádná místa. Zapněte WC nebo benzín u mapy.</p>}{facilities.map(p=><button className="facility-row" key={p.id} onClick={()=>onPlace(p.id)}><span className="facility-row-icons">{p.toilets&&<Toilet size={18}/>} {p.fuel.length>0&&<Fuel size={18}/>}</span><span><strong>{p.name}</strong><small>{p.visits.filter(v=>routes.some(r=>r.id===v.routeId)).map(v=>`${routes.find(r=>r.id===v.routeId)!.letter} · ${km(v.atKm)} km od startu`).join(' / ')}</small></span><ArrowUpRight size={16}/></button>)}<p className="small-note">Výběr míst z OpenStreetMap, nikoli úplný seznam všech provozoven. Záznam v mapě nezaručuje aktuální otevření.</p></Modal>;
}
export function FacilityDetails({facility,routes,onClose}:{facility:Facility;routes:Route[];onClose:()=>void}){
 const p=facility;
 return <Modal title={p.name} onClose={onClose}><div className="facility-badges">{p.toilets&&<span><Toilet size={20}/> Toalety</span>}{p.fuel.length>0&&<span><Fuel size={20}/> Benzín</span>}</div><h3>Co tu najdeme</h3>{p.fuel.length>0&&<p><b>Benzín:</b> {p.fuel.join(', ')} podle mapového záznamu. Cenu a aktuální dostupnost paliva nemáme ověřenou.</p>}<p><b>Toalety:</b> {p.toilets?'Uvedené v OpenStreetMap. '+p.toiletAccess:'U této stanice nejsou spolehlivě doložené.'}</p>{p.toilets&&<p><b>Poplatek za WC:</b> {p.toiletFee}</p>}<p><b>Otevírací doba:</b> {p.openingHours==='24/7'?'Nepřetržitě (údaj v mapě).':p.openingHours}</p><p className="small-note">Zvlášť při nočním příjezdu si dostupnost ověřte. Otevírací doba stanice nemusí být otevírací dobou toalety.</p><h3>Příjezd po vaší trase</h3>{p.visits.filter(v=>routes.some(r=>r.id===v.routeId)).map(v=>{const r=routes.find(r=>r.id===v.routeId)!;return <div className="facility-approach" key={v.routeId}><b>{r.letter} · {r.name}</b><p>Přibližně {km(v.atKm)} km od startu. Příjezd a návrat na trasu: +{v.detourKm.toFixed(1).replace('.',',')} km, +{Math.ceil(v.detourMinutes)} min jízdy.</p><a href={v.routingUrl} target="_blank" rel="noopener noreferrer">Podklad výpočtu příjezdu <ArrowUpRight size={14}/></a></div>;})}<p className="note">Značka sama nepřidává pauzu do itineráře. Na WC a tankování si ponechte čas ve vlastní rezervě. Sledujte místní značení vjezdu; mapový výpočet neověřuje aktuální uzavírky.</p><div className="source-links"><a href={'https://www.google.com/maps/search/?api=1&query='+p.coordinates[1]+','+p.coordinates[0]} target="_blank" rel="noopener noreferrer">Otevřít místo v Google Maps <ArrowUpRight size={16}/></a><a href={p.sourceUrl} target="_blank" rel="noopener noreferrer">Záznam OpenStreetMap <ArrowUpRight size={16}/></a></div><p className="small-note">Mapová data stažena {dateAt(p.checkedAt.slice(0,10)+'T00:00')}. Dostupnost není ověřená telefonicky. © OpenStreetMap contributors, ODbL.</p></Modal>;
}
