import {useState} from 'react';
import {Temporal} from '@js-temporal/polyfill';
import {Trash2} from 'lucide-react';
import {Money} from './Money';
import {dateAt,validLocal} from './planning';
import type {PaidPass} from './types';

const products={at1:{country:'AT',days:1,eur:9.6,name:'Rakousko · 1 den'},at10:{country:'AT',days:10,eur:12.8,name:'Rakousko · 10 dní'},si7:{country:'SI',days:7,eur:16,name:'Slovinsko 2A · 7 dní'}} as const;
type Product=keyof typeof products;
export function PaidPasses({paid,planned,onChange}:{paid:PaidPass[];planned:PaidPass[];onChange:(passes:PaidPass[])=>void}){
 const [product,setProduct]=useState<Product>('at10'),[from,setFrom]=useState('2026-09-12'),[to,setTo]=useState('2026-09-21'),[price,setPrice]=useState('12.8'),[message,setMessage]=useState('');
 function updateDates(start:string,key:Product){setFrom(start);if(validLocal(start+'T00:00'))setTo(Temporal.PlainDate.from(start).add({days:products[key].days-1}).toString());}
 function add(pass:PaidPass){if(paid.some(p=>p.country===pass.country&&p.from===pass.from&&p.to===pass.to)){setMessage('Tuto známku už máte zapsanou.');return;}if(paid.length>=20){setMessage('Lze zapsat nejvýše 20 známek.');return;}onChange([...paid,pass]);setMessage('Zakoupená známka je uložená. Ceny všech tras jsou přepočítané.');}
 const eur=Number(price.replace(',','.')),valid=validLocal(from+'T00:00')&&validLocal(to+'T00:00')&&to>=from&&price.trim()!==''&&Number.isFinite(eur)&&eur>=0&&eur<=1000;
 return <section className="paid-passes"><h3>Naše dálniční známky</h3><p>Schválené trasy sdílí plánované známky automaticky. Po nákupu zde zapište skutečnou platnost a cenu. Tímto se žádná známka nekupuje.</p>
 {paid.length>0?<dl className="cost-list">{paid.map((p,i)=><div key={p.country+p.from+p.to}><dt>{p.name}<small>Už zaplaceno · {dateAt(p.from+'T00:00')} – {dateAt(p.to+'T00:00')} včetně</small></dt><dd><Money eur={p.eur}/><button className="icon-button" aria-label={'Odebrat záznam '+p.name+' od '+dateAt(p.from+'T00:00')} onClick={()=>{onChange(paid.filter((_,n)=>n!==i));setMessage('Záznam byl odebrán. Nejde o zrušení ani vrácení skutečného nákupu.');}}><Trash2 size={16}/></button></dd></div>)}</dl>:<p className="small-note">Zatím nemáte zapsanou žádnou zahraniční známku. Českou známku už ve výpočtu považujeme za zaplacenou.</p>}
 {planned.length>0&&<><h4>Ještě ke koupi podle plánu</h4>{planned.map(p=><div className="pass-purchase" key={p.country+p.from}><span>{p.name}<small>{dateAt(p.from+'T00:00')} – {dateAt(p.to+'T00:00')} včetně · <Money eur={p.eur}/></small></span><button className="soft-button" onClick={()=>add(p)}>Už koupená</button></div>)}<p className="small-note">„Už koupená“ použijte, jen pokud souhlasí druh, platnost i cena se zakoupenou známkou. Jinak ji zapište níže.</p></>}
 <details><summary>Zapsat vlastní zakoupenou známku</summary><form onSubmit={e=>{e.preventDefault();if(valid)add({country:products[product].country,name:products[product].country==='AT'?'Rakousko · zakoupená známka':'Slovinsko 2A · zakoupená známka',from,to,eur});}}><div className="form-grid"><label className="field">Druh známky<select aria-label="Druh známky" value={product} onChange={e=>{const key=e.target.value as Product;setProduct(key);setPrice(String(products[key].eur));updateDates(from,key);}}><option value="at10">Rakousko · 10 dní</option><option value="at1">Rakousko · 1 den</option><option value="si7">Slovinsko 2A · 7 dní</option></select></label><label className="field">Zaplacená cena (€)<input inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} required/></label><label className="field">Platí od<input type="date" value={from} onChange={e=>updateDates(e.target.value,product)} required/></label><label className="field">Platí do (včetně)<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)} required/></label></div><p className="small-note">Datum konce můžete upravit podle potvrzení nákupu, například pro měsíční či roční známku. Rozhodující je skutečný začátek platnosti, ne den nákupu.</p>{valid?<p>Zaplaceno: <Money eur={eur}/></p>:<p className="error">Vyplňte platné datum a cenu od <Money eur={0}/> do <Money eur={1000}/>.</p>}<button className="primary" disabled={!valid} type="submit">Uložit zakoupenou známku</button></form></details>
 {message&&<p role="status">{message}</p>}</section>;
}
