import {describe,expect,it} from 'vitest';
import raw from '../public/data/trip.json';
import type {Dataset,Selection} from './types';
import {budget,candidateTime,clockAt,costs,countryEvents,dateAt,defaults,fuel,itinerary,moment,restore,vignettePasses} from './planning';
const data=raw as Dataset;
describe('Benzín a celkový rozpočet',()=>{
 it('zohlední rozdělené chorvatské mýto i dvě současné pauzy',()=>{const settings=defaults(data),r=data.routes.find(r=>r.id==='hr-b')!;const c=costs(r,settings,{routeId:r.id,stops:{fuzine:40,ogulin:35},reserve:0});expect(c.toll).toBeCloseTo(1.1+2.1+5+12.2);});
 it('počítá litry a stejnou cenu za litr bez předčasného zaokrouhlení',()=>{expect(fuel(650,8,1.912).liters).toBe(52);expect(fuel(650,8,1.912).eur).toBeCloseTo(99.424);expect(()=>fuel(100,NaN,2)).toThrow();});
 it('účtuje AT a SI za platnost, nikoli za počet etap',()=>{const s=defaults(data);for(const id of ['si-a','hr-a','home-a']){const r=data.routes.find(r=>r.id===id)!;s.plan[r.stage]={routeId:r.id,stops:{},reserve:0};}const b=budget(data,s);expect(b.passes).toHaveLength(2);expect(b.passes.reduce((n,p)=>n+p.eur,0)).toBeCloseTo(28.8);expect(b.toll).toBeCloseTo(19+19.2+43.9);expect(b.total).toBeCloseTo(b.gas+b.toll+28.8);});
 it('C bez SI v první etapě neodstraní známku nutnou pro druhý den',()=>{const s=defaults(data);s.plan.si={routeId:'si-c',stops:{},reserve:0};expect(budget(data,s).passes.some(p=>p.country==='SI')).toBe(false);s.plan.hr={routeId:'hr-c',stops:{},reserve:0};expect(budget(data,s).passes.find(p=>p.country==='SI')?.from).toBe('2026-09-13');});
 it('počítá pohonné hmoty i pro zajížďku',()=>{const r=data.routes[0],s=defaults(data);const c={routeId:r.id,stops:{gleinkersee:45},reserve:0};expect(costs(r,s,c).eur-costs(r,s).eur).toBeCloseTo(r.stops.find(v=>v.id==='gleinkersee')!.detourKm*.08*1.912);});
});
describe('Platnosti a časové pásmo',()=>{
 it('počítá týden včetně prvního a posledního dne',()=>{const passes=vignettePasses([{country:'SI',date:'2026-09-12'},{country:'SI',date:'2026-09-18'},{country:'SI',date:'2026-09-19'}]);expect(passes).toHaveLength(2);expect(passes[0].to).toBe('2026-09-18');});
 it('půlnoc přesune datum ve střední Evropě',()=>{expect(clockAt('2026-09-12T23:30',90)).toBe('01:00');expect(dateAt('2026-09-12T23:30',90)).toBe('13. 9. 2026');expect(moment('2026-09-12T04:00').offset).toBe('+02:00');});
 it('přičítá reálnou dobu jízdy přes změnu letního času a odmítne neexistující čas',()=>{expect(clockAt('2026-03-29T01:30',60)).toBe('03:30');expect(()=>moment('2026-03-29T02:30')).toThrow();expect(()=>moment('2026-10-25T02:30')).toThrow();});
 it('bere datum průjezdu zemí, nikoli pouze datum odjezdu',()=>{const r=data.routes.find(r=>r.id==='si-a')!;const events=countryEvents(r,'2026-09-12T23:30');expect(events.find(e=>e.country==='AT')?.date).toBe('2026-09-13');});
});
describe('Itinerář a kvalita dat',()=>{
 it('všechny příjezdy i návraty používají nový bod Branimirova obala 12',()=>{const point=[15.276598,44.078068];expect(data.stages.find(s=>s.id==='hr')!.end).toEqual(point);expect(data.stages.find(s=>s.id==='home')!.start).toEqual(point);for(const r of data.routes.filter(r=>r.stage!=='si')){const p=r.stage==='hr'?r.geometry.coordinates.at(-1)!:r.geometry.coordinates[0];expect(Math.abs(p[0]-point[0])).toBeLessThan(.001);expect(Math.abs(p[1]-point[1])).toBeLessThan(.001);}});
 it('posune následující zastávku o pobyt i celou předchozí zajížďku',()=>{const r=data.routes[0],first=r.stops.find(s=>s.id==='gleinkersee')!,later=r.stops.find(s=>s.id==='maribor')!;const s:Selection={routeId:r.id,stops:{gleinkersee:45,maribor:35},reserve:30};const t=itinerary(r,s);expect(t.stops[1].arrivalMinute).toBeCloseTo(later.atMinute+45+first.detourMinutes);expect(t.minutes).toBeCloseTo(r.drivingMinutes+45+35+first.detourMinutes+later.detourMinutes+30);expect(candidateTime(r,'maribor',s)).toBeCloseTo(t.stops[1].arrivalMinute);const changed=itinerary(r,{...s,stops:{...s.stops,gleinkersee:75}});expect(changed.minutes-t.minutes).toBe(30);const removed=itinerary(r,{...s,stops:{maribor:35}});expect(t.minutes-removed.minutes).toBeCloseTo(45+first.detourMinutes);});
 it('každá trasa má geometrii, zdroje, průjezdy v pořadí a 3–5 zastávek',()=>{for(const r of data.routes){expect(r.geometry.coordinates.length).toBeGreaterThan(100);expect(r.stops.length).toBeGreaterThanOrEqual(3);expect(r.stops.length).toBeLessThanOrEqual(5);expect(r.highwayKm).toBeLessThanOrEqual(r.distanceKm);for(const w of r.countryWindows)expect(w.end).toBeGreaterThanOrEqual(w.start);for(const s of r.stops){expect(s.detourKm).toBeGreaterThanOrEqual(0);expect(s.detourMinutes).toBeGreaterThanOrEqual(0);expect(s.atMinute).toBeLessThanOrEqual(r.drivingMinutes+s.detourMinutes);expect(data.places.find(p=>p.id===s.id)).toBeDefined();}for(const t of r.tolls)expect(data.sources.find(s=>s.id===t.source)).toBeDefined();}for(const p of data.places)for(const id of p.sources)expect(data.sources.find(s=>s.id===id)).toBeDefined();});
 it('sdílené místo má jiné silniční příjezdy pro různé trasy',()=>{const a=data.routes.find(r=>r.id==='si-a')!.stops.find(s=>s.id==='gleinkersee')!,back=data.routes.find(r=>r.id==='home-a')!.stops.find(s=>s.id==='gleinkersee')!;expect(a.atKm).not.toBe(back.atKm);expect(a.coordinates).toEqual(back.coordinates);});
 it('poškozené úložiště nezpůsobí prázdnou obrazovku ani NaN',()=>{expect(restore('{broken',data)).toEqual(defaults(data));const restored=restore(JSON.stringify({consumption:-4,fuelPrice:'wrong',plan:{si:{routeId:'not-a-route',stops:{}}}}),data);expect(restored).toEqual(defaults(data));});
});
