import {useEffect,useMemo,useRef,useState} from 'react';
import {Download,Printer} from 'lucide-react';
import type {Dataset,Route,Selection,Settings} from './types';
import {roadbookContent,roadbookCss,roadbookDocument,offlineMap,tripDocument} from './roadbookData';
function saveDocument(html:string,name:string){const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export function TripDownload({data,settings}:{data:Dataset;settings:Settings}){const [saved,setSaved]=useState(false);return <div className="trip-download"><button className="soft-button" disabled={!Object.keys(settings.plan).length} onClick={()=>{saveDocument(tripDocument(data,settings),'jedeme-spolu-mapa-a-rozpis.html');setSaved(true);}}><Download size={18}/> Stáhnout mapu a rozpis do telefonu</button><p className="small-note">Jeden soubor se všemi vybranými etapami, orientační mapou tras, zastávkami, rozpisy a poplatky. Funguje bez internetu; fotografie a podkladové mapové dlaždice neobsahuje. Po změně plánu stáhněte nový.</p>{saved&&<p role="status">Soubor byl předán ke stažení. Otevřete jej ve Stažených souborech v telefonu.</p>}</div>;}
export default function Roadbook({data,route,settings,selection}:{data:Dataset;route:Route;settings:Settings;selection?:Selection}){
 const [saved,setSaved]=useState(false);const detail=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{let wasOpen=false;const before=()=>{wasOpen=detail.current?.open??false;if(detail.current)detail.current.open=true;};const after=()=>{if(detail.current)detail.current.open=wasOpen;};window.addEventListener('beforeprint',before);window.addEventListener('afterprint',after);return()=>{window.removeEventListener('beforeprint',before);window.removeEventListener('afterprint',after);};},[]);
 const content=useMemo(()=>roadbookContent(data,route,settings,selection),[data,route,settings,selection]);
 function download(){saveDocument(roadbookDocument(offlineMap(data,[route],{...settings,plan:{[route.stage]:selection??{routeId:route.id,stops:{},reserve:0}}})+'<article id="guide-'+route.id+'">'+content+'</article>',route.name),'jedeme-spolu-'+route.id+'-'+settings.departures[route.stage].slice(0,10)+'.html');setSaved(true);}
 return <section className="roadbook"><style>{roadbookCss}</style><div className="roadbook-heading"><h3>Tahák podle silnic a cedulí</h3><div className="roadbook-actions"><button className="soft-button" onClick={download}><Download size={16}/> Uložit tahák offline</button><button className="soft-button" onClick={()=>window.print()}><Printer size={16}/> Tisk / PDF</button></div></div><p className="small-note">Uloží se samostatný HTML soubor s orientační mapou tras a pokyny; nepotřebuje další soubory. Na telefonu jej před cestou otevřete ze Stažených souborů; pro PDF použijte Tisk / PDF. Samotné otevření webu nezajišťuje dostupnost bez internetu.</p>{saved&&<p role="status" className="small-note">Soubor byl předán prohlížeči ke stažení. Ověřte jej ve Stažených souborech; po změně plánu stáhněte nový tahák.</p>}<details ref={detail} className="roadbook-details"><summary>Rozbalit podrobné pokyny a poplatky</summary><div dangerouslySetInnerHTML={{__html:content}}/></details></section>;
}
