import {describe,it,expect} from 'vitest';
import raw from '../public/data/trip.json';
import type {Dataset} from './types';
import {books,routeSteps,roadbookContent,roadbookDocument,tripDocument} from './roadbookData';
import {defaults} from './planning';
const data=raw as Dataset;
describe('Taháky pro jízdu podle silnic',()=>{
 it('mají úplnou návaznost všech 12 základních tras a české pokyny',()=>{expect(Object.keys(books)).toHaveLength(12);for(const r of data.routes){const rows=routeSteps(r);expect(rows.length).toBeGreaterThan(25);expect(rows[0].atKm).toBe(0);expect(rows.at(-1)!.atKm).toBeCloseTo(r.distanceKm,1);for(let i=0;i<rows.length-1;i++){expect(rows[i].text).not.toMatch(/\b(Take|Enter|Turn|Keep|Drive|Continue|toward|onto)\b/);expect(rows[i].atKm+rows[i].lengthKm).toBeCloseTo(rows[i+1].atKm,1);}}});
 it('zachová číslo sjezdu i směry a nevymýšlí označení',()=>{expect(books['si-a'].steps.some(s=>s.text.includes('sjezd 21')&&s.text.includes('Linz/České Budějovice/Benešov'))).toBe(true);expect(books['si-c'].steps.some(s=>s.roads.includes('410'))).toBe(true);});
 it('každou vybranou zastávku vloží s návratem a bez původního souběžného úseku',()=>{for(const r of data.routes)for(const stop of r.stops){const rows=routeSteps(r,{routeId:r.id,stops:{[stop.id]:45},reserve:0});expect(rows.filter(s=>s.text.startsWith('Zastávka:'))).toHaveLength(1);expect(rows.at(-1)!.atKm).toBeGreaterThan(r.distanceKm-.1);for(let i=0;i<rows.length-1;i++)expect(rows[i].atKm+rows[i].lengthKm).toBeCloseTo(rows[i+1].atKm,1);}});
 it('dvě odbočky vloží v pořadí a aktualizuje cenu i jména v exportu',()=>{const r=data.routes.find(r=>r.id==='hr-b')!,s=defaults(data),choice={routeId:r.id,stops:{fuzine:40,ogulin:35},reserve:0};const rows=routeSteps(r,choice);expect(rows.filter(s=>s.text.startsWith('Zastávka:')).map(s=>s.text)).toEqual(['Zastávka: fuzine · pobyt 40 min.','Zastávka: ogulin · pobyt 35 min.']);const html=roadbookContent(data,r,s,choice);expect(html).toContain('Fužine');expect(html).toContain('Ogulin');expect(html).toContain('Úprava základního mýta');});
 it('export rozlišuje zaplacené známky a skutečnou nákupní cenu, není závislý na webových souborech',()=>{const s=defaults(data);s.plan.si={routeId:'si-a',stops:{},reserve:0};s.paidPasses=[{country:'SI',from:'2026-09-12',to:'2026-09-18',eur:16,name:'Slovinsko'}];const html=roadbookDocument(roadbookContent(data,data.routes.find(r=>r.id==='home-a')!,s),'Test <script>');expect(html).toContain('už zaplaceno');expect(html).toContain('18. 9. 2026');expect(html).toContain('12,80');expect(html).not.toMatch(/<script|<img|<link|<iframe|\ssrc=/i);expect(html).toContain('&lt;script&gt;');expect(html).toContain('shop.asfinag.at');});
});

it('celý plán obsahuje samostatnou SVG mapu a jen schválené etapy',()=>{const s=defaults(data);s.plan.si={routeId:'si-a',stops:{gleinkersee:45},reserve:0};s.plan.home={routeId:'home-a',stops:{},reserve:0};const html=tripDocument(data,s);expect(html).toContain('<svg');expect(html).toContain('id="guide-si-a"');expect(html).toContain('id="guide-home-a"');expect(html).not.toContain('id="guide-hr-');expect(html).toContain('Gleinkersee');expect(html).toContain('2 ze 3');expect(html).not.toMatch(/<script|<img|<link|<iframe|\ssrc=|NaN/i);});
