import raw from '../data/roadbooks.json';
import type {Dataset,Point,Route,Selection,Settings} from './types';
import {budget,comparisonCosts,countryEvents,dateAt,dateTime,itinerary,passCovers} from './planning';
import {currency} from './currency';
export interface RoadStep{atKm:number;lengthKm:number;text:string;original:string;roads:string[];point:Point;type:number;rough:boolean}
interface Book{steps:RoadStep[];detours:Record<string,{legs:RoadStep[][];checkedAt:string}>;checkedAt:string}
export const books=raw as unknown as Record<string,Book>;
export function routeSteps(route:Route,selection?:Selection){
 const book=books[route.id],out:RoadStep[]=[];let cursor=0,offset=0;
 function base(from:number,to:number){for(const s of book.steps){if(s.lengthKm===0||s.atKm>=to||s.atKm+s.lengthKm<=from)continue;const start=Math.max(from,s.atKm),end=Math.min(to,s.atKm+s.lengthKm);out.push({...s,atKm:start+offset,lengthKm:end-start,...(start>s.atKm+.001?{text:'Pokračujte po '+(s.roads.join(' / ')||'této silnici')+'.',original:'',point:s.point}:{})});}}
 for(const stop of itinerary(route,selection).stops){const v=stop.visit;base(cursor,v.fromKm);const legs=book.detours[v.id].legs,origin=v.fromKm+offset;
  for(let i=0;i<legs.length;i++)for(const s of legs[i]){
   if(s.lengthKm===0){if(i===0)out.push({...s,atKm:origin+s.atKm,text:'Zastávka: '+v.id+' · pobyt '+stop.duration+' min.',original:''});continue;}
   out.push({...s,atKm:origin+s.atKm});
  }
  const last=legs[1].at(-1)!;offset+=last.atKm-(v.toKm-v.fromKm);cursor=v.toKm;
 }
 base(cursor,Infinity);const end=book.steps.at(-1)!;out.push({...end,atKm:end.atKm+offset});return out;
}
export const escapeHtml=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const h=escapeHtml;
const number=(n:number)=>n.toLocaleString('cs-CZ',{maximumFractionDigits:1});
export const roadbookCss=`.roadbook-content{color:#192d31;font:15px/1.6 'Segoe UI',Arial,sans-serif;overflow-wrap:anywhere}.roadbook-content h2{font-size:24px}.roadbook-content h3{margin-top:24px;font-size:19px}.roadbook-content p{margin:10px 0}.roadbook-content .rb-note{border-left:3px solid #b72150;padding:12px;background:#fcf0f4}.roadbook-content li{padding:12px 0;border-bottom:1px solid #dde5e5;break-inside:avoid}.roadbook-content ol{padding-left:26px}.roadbook-content strong{font-weight:700}.roadbook-content small{display:block;color:#54676d}.roadbook-content a{color:#b72150}.roadbook-content .rb-fee{border:1px solid #dde5e5;border-radius:8px;padding:14px;margin:12px 0;break-inside:avoid}.roadbook-content details{margin:8px 0}.roadbook-content summary{cursor:pointer}.roadbook-content .rb-original{font-size:12px;color:#54676d} @media print{.roadbook-content{font-size:11pt}.roadbook-content details>*{display:block!important}.roadbook-content .rb-original{display:none!important}.roadbook-content a{color:inherit;text-decoration:none}.roadbook-content h2,.roadbook-content h3{break-after:avoid} }`;
function link(url:string,label:string){return `<a href="${h(url)}" target="_blank" rel="noopener noreferrer">${h(label)}</a>`;}
export function roadbookContent(data:Dataset,route:Route,settings:Settings,selection?:Selection){
 const price=comparisonCosts(data,route,settings,selection),trip=itinerary(route,selection),events=countryEvents(route,settings.departures[route.stage],selection);
 const candidate={...settings,plan:{...settings.plan,[route.stage]:selection??{routeId:route.id,stops:{},reserve:0}}},planned=budget(data,candidate).passes;
 const money=(eur:number)=>h(currency(eur*settings.exchangeRate,'CZK')+' / '+currency(eur,'EUR'));
 const passes=[...settings.paidPasses.map(p=>({...p,paid:true})),...planned.map(p=>({...p,paid:false}))].filter(p=>events.some(e=>passCovers(p,e)));
 const fees=passes.map(p=>`<div class="rb-fee"><strong>${h(p.name)} · ${p.paid?'už zaplaceno':'ještě koupit'}</strong><p>${money(p.eur)} ${p.paid?'zapsaná cena; nový výdaj '+money(0):'cena celého produktu, ne pouze rozdíl v rozpočtu'}.</p><p>Platnost ${dateAt(p.from+'T00:00')} – ${dateAt(p.to+'T00:00')} včetně. ${p.country==='AT'?'Jednodenní platí do půlnoci daného dne; desetidenní první den + 9 dalších.':'Týdenní platí první den + 6 dalších.'}</p></div>`).join('');
 const at=route.vignettes.includes('AT')?`<p><strong>Rakousko — koupit před vjezdem na zpoplatněnou dálnici.</strong> ${link('https://shop.asfinag.at/en/','Oficiální obchod ASFINAG (shop.asfinag.at)')}, aplikace ASFINAG, autorizovaná prodejní místa nebo automaty. Pro 1denní/10denní digitální známku lze zvolit okamžitou platnost, 18denní čekání se na ně nevztahuje. Ověřte SPZ, zemi registrace a datum. Bez internetu použijte autorizované fyzické místo ještě před placeným úsekem, ne první pumpu až za hranicí.</p>`:'';
 const si=route.vignettes.includes('SI')?`<p><strong>Slovinsko — e-viněta 2A před vjezdem na dálnici.</strong> ${link('https://evinjeta.dars.si/en','Oficiální obchod DARS (evinjeta.dars.si)')}, střediska DarsGo nebo autorizovaní prodejci. Online kartou lze zvolit okamžitou platnost; potvrzení a správnou SPZ si uložte. Týdenní standardně ${money(16)}. ${link('https://evinjeta.dars.si/en/how-buy','Postup a prodejní místa DARS')}.</p>`:`<p>Slovinská známka na této uložené trase není potřeba. ${route.id==='si-c'?'Za Ljubeljem dodržte místní silnice v pokynech; neodbočujte na A2.':''}</p>`;
 const tollOrder=route.stage==='home'?['Zagreb','Zaprešić','Bregana','Karav','Gleinalm','Bosruck','Tauern']:[];
 const orderedTolls=route.stage==='home'?[...route.tolls].sort((a,b)=>tollOrder.findIndex(n=>a.name.includes(n))-tollOrder.findIndex(n=>b.name.includes(n))):route.tolls;
 const tolls=orderedTolls.map(t=>`<div class="rb-fee"><strong>${h(t.name)} · ${money(t.eur)}</strong><p>${t.source==='at-tolls'?'Za jeden průjezd. Koupit v obchodě ASFINAG předem nebo zaplatit na mýtnici kartou/hotovostí podle označení pruhu. Jednorázový předkoupený průjezd lze využít do jednoho roku; neznamená neomezené jízdy po rok.':t.source==='karavanky-si'?'Směr Slovinsko → Rakousko: zaplatit u mýtnice Hrušica provozovateli DARS, za jeden průjezd. Nákup rakouského produktu pro opačný směr jej nenahrazuje.':'Platba za tento průjezd na mýtnici v EUR nebo kartou podle označení pruhu; nejde o časovou dálniční známku.'}</p>${link(data.sources.find(s=>s.id===t.source)!.url,'Ceník provozovatele')}</div>`).join('');
 const adjustments=(route.tollAdjustments??[]).filter(a=>selection?.stops[a.stopId]!==undefined).map(a=>`<p>Úprava základního mýta kvůli zastávce ${h(data.places.find(p=>p.id===a.stopId)!.name)}: ${money(a.eur)}. Při sjezdu zaplatíte projetý úsek, při opětovném nájezdu si vezmete nový lístek; výše uvedená základní cena se tím rozdělí. ${link(data.sources.find(s=>s.id===a.source)!.url,'Ceník sjezdu')}</p>`).join('');
 const hr=route.stage!=='si'?`<p><strong>Chorvatsko:</strong> na uzavřeném systému HAC při nájezdu vezměte lístek, uschovejte jej a odevzdejte při výjezdu; plaťte EUR nebo kartou. Bregana/Rupa mají přímou platbu za průjezd. Bez ENC nepoužívejte pruh označený pouze ENC. U Zagreb–Macelj provozuje výběr AZM. ${link('https://www.hac.hr/en/toll','HAC — způsob platby')} · ${link('https://www.azm.hr/en/toll-system/payment-system-on-azm-c11','AZM — platba')}.</p>`:'';
 const rows=routeSteps(route,selection).map((s,i)=>{let text=s.text;for(const p of data.places)text=text.replace('Zastávka: '+p.id+' ·','Zastávka: '+p.name+' ·');return `<li><small>Od startu přibližně ${number(s.atKm)} km · úsek ${s.lengthKm<1?Math.round(s.lengthKm*1000)+' m':number(s.lengthKm)+' km'}</small><strong>${h(text)}</strong>${s.roads.length?'<small>Silnice / ulice: '+h(s.roads.join(' / '))+'</small>':''}${s.rough?'<small>Mapová data uvádějí horší povrch; ověřte příjezd.</small>':''}${s.original?`<details class="rb-original"><summary>Původní pokyn z mapových dat · ${i+1}</summary>${h(s.original)}</details>`:''}</li>`;}).join('');
 return `<div class="roadbook-content"><h2>${h(route.letter+' · '+route.name)}</h2><p>${h(route.via)}</p><p>Odjezd ${dateTime(settings.departures[route.stage])}; příjezd podle plánu ${dateTime(settings.departures[route.stage],trip.minutes)}. Plán ${number(trip.distanceKm)} km, ${trip.stops.length} vybraných zastávek. Přepočet 1 € = ${settings.exchangeRate.toLocaleString('cs-CZ',{maximumFractionDigits:4})} Kč.</p><p class="rb-note">Tahák si stáhněte před odjezdem a zkuste otevřít uložený soubor bez připojení. Pokyny jsou z uložené silniční trasy (${dateAt(books[route.id].checkedAt.slice(0,10)+'T00:00')}), nikoli živé navigace. Názvy směrů a sjezdy pocházejí z mapových dat, fyzické cedule nejsou ověřené na místě. Při uzavírce nebo rozdílném značení se řiďte aktuálními cedulemi; v případě nejistoty zastavte na bezpečném místě. Kilometry jsou orientační vzdálenost od startu, ne dálniční kilometrovníky. Tahák čte spolujezdec nebo řidič při zastavení.</p><h3>Před cestou: známky a platby</h3><p>Česká známka již koupená: nově ${money(0)}. Ostatní známky se sdílí podle platnosti. Zde je cena celých produktů; souhrn níže odlišuje nový výdaj oproti ostatním etapám.</p>${fees}${at}${si}<h3>Mýtnice a jednotlivé průjezdy</h3>${tolls||'<p>Na základní trase není další úsekové mýto.</p>'}${adjustments}${hr}<p><strong>Mýto včetně zvolených sjezdů: ${money(price.toll)}. Benzín: ${money(price.eur)}. Známky navíc oproti ostatním etapám: ${money(price.passTotal)}. Celkem navíc: ${money(price.total)}.</strong> Plánované doplatky nejsou samostatně prodejné produkty. Dokud nepotvrdíte skutečný nákup v rozpočtu, známka není považována za zaplacenou.</p><p>Pravidla nákupu/platnosti ověřena 11. 9. 2026, výchozí mýtné tarify aplikace 8. 9. 2026. ${link('https://www.asfinag.at/en/toll/section-toll/','ASFINAG — úseky a platnost')} · ${link('https://evinjeta.dars.si/en/e-vignette-validity','DARS — platnost')}.</p><h3>Podrobná cesta krok za krokem</h3><p>${route.stage==='si'?'Start je uložený bod v Průhonicích, ne konkrétní bydliště. ':''}${route.stage==='home'?'Cílem je uložený bod v Průhonicích.':'Závěrečný příjezd k ubytování může vést po nepojmenované cestě; přesný vjezd si potvrďte s hostitelem.'} ${route.stage!=='home'?'Cílová adresa: '+h(route.stage==='si'?'Kamniška Bistrica 8, 1242 Stahovica':'Branimirova obala 12, 23205 Bibinje')+'. ':''}Příjezdy k vybraným zastávkám jsou vložené do pořadí; kilometry se po zajížďce přepočítají.</p><ol>${rows}</ol><p>Zdroj pokynů: Valhalla / © OpenStreetMap contributors. ${link('https://www.openstreetmap.org/copyright','Licence mapových dat')}. Tento uložený soubor je snímek plánu; po změně trasy, pauz nebo známek stáhněte nový.</p></div>`;
}
export function roadbookDocument(content:string,title:string){return `<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${h(title)}</title><style>body{max-width:850px;margin:auto;padding:20px;background:white}${roadbookCss}</style></head><body>${content}</body></html>`;}

export function offlineMap(data:Dataset,routes:Route[],settings:Settings){
 const points=routes.flatMap(r=>[...r.geometry.coordinates,...r.stops.filter(v=>settings.plan[r.stage]?.stops[v.id]!==undefined).flatMap(v=>v.geometry)]);
 if(!points.length)return '';
 const project=(p:number[])=>[p[0],-Math.log(Math.tan(Math.PI/4+p[1]*Math.PI/360))*180/Math.PI];
 const xy=points.map(project),xs=xy.map(p=>p[0]),ys=xy.map(p=>p[1]),xmin=Math.min(...xs),ymin=Math.min(...ys),width=Math.max(...xs)-xmin,height=Math.max(...ys)-ymin,scale=Math.min(660/(width||1),660/(height||1));
 const position=(p:number[])=>{const q=project(p);return [70+(q[0]-xmin)*scale,50+(q[1]-ymin)*scale];};
 const line=(points:number[][])=>points.map(p=>position(p).map(n=>n.toFixed(1)).join(',')).join(' ');
 const markers=new Map<string,{name:string;point:number[]}>();
 for(const r of routes){const stage=data.stages.find(s=>s.id===r.stage)!;markers.set(stage.from,{name:stage.from,point:stage.start});markers.set(stage.to,{name:stage.to,point:stage.end});for(const v of r.stops)if(settings.plan[r.stage]?.stops[v.id]!==undefined)markers.set(v.id,{name:data.places.find(p=>p.id===v.id)!.name,point:v.coordinates});}
 const paths=routes.map(r=>'<a href="#guide-'+h(r.id)+'"><polyline fill="none" stroke="'+h(r.color)+'" stroke-width="4" points="'+line(r.geometry.coordinates)+'"><title>'+h(r.name)+'</title></polyline></a>'+r.stops.filter(v=>settings.plan[r.stage]?.stops[v.id]!==undefined).map(v=>'<polyline fill="none" stroke="'+h(r.color)+'" stroke-width="3" stroke-dasharray="5 4" points="'+line(v.geometry)+'"/>').join('')).join('');
 const labels=[...markers.values()].map((m,i)=>{const [x,y]=position(m.point);return '<circle cx="'+x+'" cy="'+y+'" r="10" fill="white" stroke="#192d31"/><text x="'+x+'" y="'+(y+4)+'" text-anchor="middle" font-size="11">'+(i+1)+'</text>';}).join('');
 return '<section class="roadbook-content"><h2>Mapa uložených tras</h2><p>Sever je nahoře. Barevné čáry jsou uložené silniční trasy, přerušované čáry zajížďky k vybraným zastávkám. Jde o orientační mapu bez podkladových mapových dlaždic a bez sledování polohy; podrobné odbočky a názvy směrů jsou níže. Kliknutím na trasu přejdete na její rozpis.</p><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 760" role="img" aria-label="Mapa vybraných tras" style="width:100%;max-height:760px;background:#f4f8f9;border:1px solid #dde5e5"><text x="20" y="30" font-size="16">↑ N</text>'+paths+labels+'</svg><ol>'+[...markers.values()].map(m=>'<li>'+h(m.name)+'</li>').join('')+'</ol><p>'+routes.map(r=>'<a href="#guide-'+h(r.id)+'">'+h(data.stages.find(s=>s.id===r.stage)!.title+' · '+r.letter+' · '+r.name)+'</a>').join(' · ')+'</p></section>';
}
export function tripDocument(data:Dataset,settings:Settings){
 const routes=data.stages.flatMap(s=>{const choice=settings.plan[s.id];return choice?[data.routes.find(r=>r.id===choice.routeId)!]:[];}),total=budget(data,settings),money=(eur:number)=>h(currency(eur*settings.exchangeRate,'CZK')+' / '+currency(eur,'EUR'));
 const intro='<section class="roadbook-content"><h1>Jedeme spolu · uložený plán cesty</h1><p>Uložené etapy: '+routes.length+' ze 3. '+(routes.length<3?'Nezvolené etapy tento soubor neobsahuje.':'')+'</p><p>Celkový rozpočet vybraného plánu: '+money(total.total)+'. Již zaplaceno: '+money(total.paidTotal)+'. Zbývající odhad: '+money(total.remaining)+'.</p><p>Tento soubor funguje samostatně bez internetu. Po změně plánu stáhněte nový. Fotografie a plná podkladová mapa se neukládají. Odkazy na prodejce vyžadují internet.</p></section>';
 return roadbookDocument(intro+offlineMap(data,routes,settings)+routes.map(r=>'<article id="guide-'+h(r.id)+'" style="break-before:page">'+roadbookContent(data,r,settings,settings.plan[r.stage])+'</article>').join(''),'Jedeme spolu · mapa a rozpis cesty');
}
